#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/.."

echo Running tests

test_args=(-mod=vendor -cover -tags=test)
if [ "${ARCH:-amd64}" = amd64 ]; then
    test_args+=(-race)
fi
go test "${test_args[@]}" ./...
