#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/.."

PACKAGES=". $(find . -name '*.go' -not -path './vendor/*' -not -path './.git/*' -not -path './bin/*' -printf '%h\n' | sort -u | grep -v '^\.$' | sed -e 's!^!./!' -e 's!$!/...!')"

echo "Running go vet"
go vet ${PACKAGES}
echo "Running gofmt"
test -z "$(find . -name '*.go' -not -path './vendor/*' -not -path './.git/*' -not -path './bin/*' -print0 | xargs -0 gofmt -l -s | tee /dev/stderr)"
